package com.triings.trringscommon.utils;

public class UserPermissions {
    public static final String CREATE_USER = "CREATE_USER";
    public static final String GET_ALL_USERS = "GET_ALL_USERS";
    public static final String GET_USER_BY_UUID = "GET_USER_BY_UUID";
    public static final String UPDATE_USER_STATUS = "UPDATE_USER_STATUS";
    public static final String UPDATE_USER_VERIFY_STATUS = "UPDATE_USER_VERIFY_STATUS";
    public static final String DELETE_USER = "DELETE_USER";
    public static final String UPDATE_USER = "UPDATE_USER";
    public static final String SET_USER_PROFILE_PICTURE = "SET_USER_PROFILE_PICTURE";
    public static final String GET_USER_ROLE_BY_UUID = "GET_USER_ROLE_BY_UUID";
    public static final String GET_USER_PERMISSIONS_BY_UUID = "GET_USER_PERMISSIONS_BY_UUID";
    public static final String SEARCH_USER_BY_IMAGE = "SEARCH_USER_BY_IMAGE";
    public static final String CREATE_CITY = "CREATE_CITY";
    public static final String UPDATE_CITY = "UPDATE_CITY";
    public static final String GET_ALL_CITY = "GET_ALL_CITY";
    public static final String DELETE_CITY = "DELETE_CITY";
    public static final String CREATE_COUNTRY = "CREATE_COUNTRY";
    public static final String UPDATE_COUNTRY = "UPDATE_COUNTRY";
    public static final String DELETE_COUNTRY = "DELETE_COUNTRY";
    public static final String CREATE_PERMISSION = "CREATE_PERMISSION";
    public static final String GET_ALL_PERMISSIONS = "GET_ALL_PERMISSIONS";
    public static final String GET_PERMISSION_BY_CODE = "GET_PERMISSION_BY_CODE";
    public static final String UPDATE_PERMISSION_STATUS = "UPDATE_PERMISSION_STATUS";
    public static final String DELETE_PERMISSION = "DELETE_PERMISSION";
    public static final String UPDATE_PERMISSION = "UPDATE_PERMISSION";
    public static final String CREATE_ROLE = "CREATE_ROLE";
    public static final String UPDATE_ROLE_PERMISSIONS = "UPDATE_ROLE_PERMISSIONS";
    public static final String GET_ALL_ROLES = "GET_ALL_ROLES";
    public static final String GET_ROLE_BY_NAME = "GET_ROLE_BY_NAME";
    public static final String UPDATE_ROLE_STATUS = "UPDATE_ROLE_STATUS";
    public static final String DELETE_ROLE = "DELETE_ROLE";
    public static final String UPDATE_ROLE = "UPDATE_ROLE";
    public static final String FOLLOW_USER = "FOLLOW_USER";
    public static final String REMOVE_FOLLOWING_USER = "REMOVE_FOLLOWING_USER";
    public static final String CREATE_COMMENT = "CREATE_COMMENT";
    public static final String DELETE_COMMENT = "DELETE_COMMENT";
    public static final String GET_COMMENT_BY_COMMENT_ID = "GET_COMMENT_BY_COMMENT_ID";
    public static final String LIKE_COMMENT = "LIKE_COMMENT";
    public static final String GET_ALL_COMMENTS_BY_POST_ID = "GET_ALL_COMMENTS_BY_POST_ID";
    public static final String CREATE_INTEREST = "CREATE_INTEREST";
    public static final String UPDATE_INTEREST = "UPDATE_INTEREST";
    public static final String DELETE_INTEREST = "DELETE_INTEREST";
    public static final String GET_ALL_INTEREST = "GET_ALL_INTEREST";
    public static final String UPDATE_USER_INTERESTS = "UPDATE_USER_INTERESTS";
    public static final String CREATE_POST = "CREATE_POST";
    public static final String UPDATE_POST = "UPDATE_POST";
    public static final String GET_ALL_POSTS = "GET_ALL_POSTS";
    public static final String GET_POSTS_BY_USER_ID = "GET_POSTS_BY_USER_ID";
    public static final String GET_POST_DETAILS_BY_POST_ID = "GET_POST_DETAILS_BY_POST_ID";
    public static final String DELETE_POST = "DELETE_POST";
    public static final String REPOST_A_POST = "REPOST_A_POST";
    public static final String UPDATE_POST_STATUS = "UPDATE_POST_STATUS";
    public static final String LIKE_POST = "LIKE_POST";
    public static final String UPDATE_POST_VIEW_COUNT = "UPDATE_POST_VIEW_COUNT";
    public static final String GET_POSTS_TAILORED_FOR_YOU = "GET_POSTS_TAILORED_FOR_YOU";
    public static final String GET_POSTS_KEENLY_WATCHING = "GET_POSTS_KEENLY_WATCHING";
    public static final String GET_ALL_POST_ADMIN = "GET_ALL_POST_ADMIN";
    public static final String CREATE_SPAM = "CREATE_SPAM";
    public static final String GET_ALL_SPAMS = "GET_ALL_SPAMS";
    public static final String DELETE_SPAM = "DELETE_SPAM";
    public static final String UPDATE_SPAM_STATUS = "UPDATE_SPAM_STATUS";
    public static final String CREATE_SPAM_REASON = "CREATE_SPAM_REASON";
    public static final String GET_ALL_SPAM_REASONS = "GET_ALL_SPAM_REASONS";
    public static final String DELETE_SPAM_REASON = "DELETE_SPAM_REASON";
    public static final String UPDATE_SPAM_REASON = "UPDATE_SPAM_REASON";
    public static final String CREATE_STORY = "CREATE_STORY";
    public static final String GET_ALL_STORIES = "GET_ALL_STORIES";
    public static final String DELETE_STORY = "DELETE_STORY";
    public static final String LIKE_STORY = "LIKE_STORY";
    public static final String GET_ALL_STORIES_ADMIN = "GET_ALL_STORIES_ADMIN";
    public static final String UPDATE_STORY_VIEW_COUNT = "UPDATE_STORY_VIEW_COUNT";
    public static final String GET_STORIES_BY_USER_ID = "GET_STORIES_BY_USER_ID";

    public UserPermissions() {
    }
}
